Repository Swifty9/Maverick-AI, pull requests merged in 2024-11, with the labels that each got.

#1 Added New official name
  src/components/Navbar.tsx
Labels: bug

#2 Added proper name
  src/components/Navbar.tsx
Labels: bug, enhancement

#4 Added Image for tab section
  image.png
  index.html
  src/assets/image.png
Labels: enhancement, help wanted

#5 Add About, Pricing, Features page
  src/App.tsx
  src/components/Navbar.tsx
  src/pages/about.tsx
  src/pages/features.tsx
  src/pages/pricing.tsx
Labels: bug, help wanted, add pages

#17 feat: implemented contributors page
  LICENSE
  src/App.tsx
  src/assets/WhatsApp Image 2024-11-16 at 02.57.32.jpeg
  src/assets/WhatsApp Image 2024-11-16 at 02.57.53.jpeg
  src/assets/WhatsApp Image 2024-11-16 at 02.59.07.jpeg
  src/components/Navbar.tsx
  src/pages/Contributors.tsx
Labels: documentation, enhancement, add pages

#19 feat: Add real-time contributor tracking system
  .github/workflows/sync-contributors.yml
  .gitignore
  package-lock.json
  package.json
  scripts/syncContributors.js
  src/App.tsx
  src/lib/contributorSync.ts
  src/lib/github.ts
  src/lib/supabase.ts
  src/pages/Contributors.tsx
  src/scripts/syncContributors.ts
Labels: enhancement

#25 feat(docker): Implement complete Docker setup with environment handling
  .dockerignore
  Dockerfile
  docker-compose.yml
  nginx.conf
  package.json
  public/index.html
  public/vite.svg
  start-app.sh
  vercel.json
  vite.config.ts
Labels: enhancement

#38 fix: Updated GitHub Actions
  .github/workflows/sync-contributors.yml
  src/lib/github.ts
Labels: enhancement

#44 Added detailed system architecture documentation using Mermaid.js dia…
  docs/architecture/data-flow.md
  docs/architecture/database-schema.md
  docs/architecture/deployment.md
  docs/architecture/system-components.md
Labels: documentation, enhancement

#46 feat: Enhanced Content Moderation with Dual AI Model Integration
  package-lock.json
  package.json
  src/lib/huggingface.ts
  src/lib/moderation.ts
Labels: enhancement

#60 Update global.tsx
  src/pages/global.tsx
Labels: bug, enhancement, frontend

#63 Merge branch 'main' of https://github.com/Swifty9/Maverick-AI
  src/pages/global.tsx
Labels: enhancement, good first issue

#64 Delete vercel.json File
  vercel.json
Labels: bug, security, backend

#65 Made changes in Mermaid File
  README.md
Labels: bug, documentation, enhancement

#66 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#68 Fix issue #14 : enables multiple option to download the report
  package-lock.json
  package.json
  src/components/DropdownButton.tsx
  src/pages/Results.tsx
Labels: enhancement, frontend

#72 Add Hover Effect and Animation to Card
  package-lock.json
  package.json
  src/pages/Home.tsx
  src/pages/about.tsx
  src/pages/features.tsx
  src/pages/global.tsx
  src/pages/pricing.tsx
  tailwind.config.js
Labels: documentation, good first issue, frontend

#70 fix: resolve DropdownButton type errors and improve download function
  package-lock.json
  package.json
  src/components/DropdownButton.tsx
  src/lib/mockHuggingface.ts
  src/lib/moderation.ts
  src/pages/Results.tsx
Labels: enhancement, frontend

#74 Added missing Background color of icons in cards
  src/pages/Home.tsx
  src/pages/about.tsx
  src/pages/features.tsx
Labels: bug, enhancement, good first issue, frontend

#77 Add AI contributing guidelines
  README.md
Labels: documentation

#89 CI/CD Issue
  authentication/supabaseClient.js
  src/lib/contributorSync.ts
Labels: devops

#92 Feature: Adds copy to clipboard functionality
  src/components/CopyButton.tsx
Labels: frontend, feature

#90 Fixes #24
  package-lock.json
  src/components/DropdownButton.tsx
Labels: bug, good first issue, feature

#94 Added missing Login Button on Navbar
  src/components/Navbar.tsx
Labels: bug, frontend

#98 feat: migrate from tensorflow.js to Mistral-7B for content moderation
  package-lock.json
  package.json
  src/lib/huggingface.ts
  src/lib/mistralService.ts
  src/lib/mockHuggingface.ts
  src/lib/moderation.ts
  src/lib/types.ts
  src/pages/ModerateText.tsx
  src/pages/Results.tsx
Labels: enhancement, AI

#100 Commented out Dummy Image Source
  src/pages/logIn.tsx
Labels: bug

#101 Added proper Docker Path
  docker-compose.yml
  package.json
Labels: documentation, security, help wanted

#103 fix: Deployment Issue
  src/lib/mistralService.ts
Labels: enhancement, AI

#106 Added Demo Page
  src/App.tsx
  src/pages/Home.tsx
  src/pages/demoTextModeration.tsx
Labels: frontend, AI, feature

#111 fix: improve mobile viewport responsiveness
  .gitignore
  index.html
  package.json
  src/App.tsx
  src/components/Navbar.tsx
  src/components/ScrollSection.tsx
  src/hooks/useIsMobile.ts
  src/index.css
  src/lib/contributorSync.ts
  src/lib/supabase.ts
  src/pages/Home.tsx
  src/pages/about.tsx
  src/pages/features.tsx
  src/scripts/syncContributors.ts
  vite.config.ts
Labels: enhancement, frontend

#117 fix: update GitHub footer link to correct repository
  src/components/Footer.tsx
Labels: frontend
